# Workflow для генерации и деплоя документации на GitHub Pages
name: Deploy Documentation to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen

      # Generate documentation using Doxygen
      - name: Generate documentation
        run: doxygen Doxyfile

      # Make the documentation directory
      - name: Make documentation directory
        run: mkdir -p docs/html

      # Copy the generated documentation to the docs directory
      - name: Copy documentation
        run: cp -r html/* docs/html/

      - name: Deploy to GitHub Pages
        uses: github/pages@v3
        with:
          out_dir: 'docs/html'
          github_token: ${{ github.token }}
          repository_name: sh77ma/calcdef
