name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Generate docs
        run: |
          make docs
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages@v1
        with:
          directory: docs